# Imagen base para Python
FROM python:3.9-slim

# Establecemos el directorio de trabajo
WORKDIR /python

# Copiamos los archivos necesarios
COPY python/requirements.txt requirements.txt
COPY python/index.py index.py

# Instalamos las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto 5000 
EXPOSE 5000

# Ejecutar el comando de inicio de Python
CMD ["python", "index.py"]